services:
  - type: web
    name: color-analysis-backend
    runtime: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: ALLOWED_ORIGIN
        value: "*"
